server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.76.129:3306/guli_cart
    username: root
    password: root
  redis:
    host: 192.168.76.129
  task:
    execution:
      thread-name-prefix: cart-async-
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 1000
        keep-alive: 60s
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.76.129
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true

auth:
  jwt:
    pubKeyPath: D:\内网通文件\锋哥\project-0713\rsa\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: user-key
    espire: 15552000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
